site_name: THS and TAMD Outside of Reaper

theme:
  name: material
  features:
    - navigation.footer
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - search
  - glightbox:
      background: none
  - redirects:
      redirect_maps:
        'Main_Guide/MCM_THS_Stem_Buses.md' : 'Main_Guide/MCM_THS_Stem_Busses.md'
        'Main_Guide/SCM_THS_Stem_Buses.md' : 'Main_Guide/SCM_THS_Stem_Busses.md'
        'Main_Guide/TAMD_Stem_Buses.md'    : 'Main_Guide/TAMD_Stem_Busses.md'

nav:
  - Main Guide:
    - Overview: Main_Guide/Overview.md
    - Getting Started:
      - Plugins: Main_Guide/Plugins.md
      - JSFX Modifications: Main_Guide/JSFX_Mods.md
      - Routing for THS and TAM(D): Main_Guide/Routing_Structure.md
    - Setting up THS:
      - Current Methods: Main_Guide/Connectivity.md
      - Universal Methods:
        - Metaplugin and Connector Method:
          - DAW-Specific Considerations: Main_Guide/MCM_DAW_Considerations.md
          - Stem Busses: Main_Guide/MCM_THS_Stem_Busses.md
          - Master Bus: Main_Guide/MCM_THS_Master_Bus.md
        - Sidechain Method:
          - Stem Busses: Main_Guide/SCM_THS_Stem_Busses.md
          - Master Bus: Main_Guide/SCM_THS_Master_Bus.md
      - DAW-Specific Methods:
        - Logic Pro:
          - Known Issues: Main_Guide/LP_Issues.md
          - Project Setup: Main_Guide/LP_Setup.md
          - Tracks: Main_Guide/LP_Tracks.md
          - Stem Busses: Main_Guide/LP_Stem_Busses.md
          - Master Bus: Main_Guide/LP_Master_Bus.md
    - Setting up TAM(D):  
      - DAW-Specific Considerations: Main_Guide/TAMD_DAW_Considerations.md
      - Channels: Main_Guide/TAMD_Channels.md
      - Stem Busses: Main_Guide/TAMD_Stem_Busses.md
      - FX Sends: Main_Guide/TAMD_FX_Sends.md
      - Master Bus: Main_Guide/TAMD_Master_Bus.md
    - Example Sessions:
      - Metaplugin and Connector Session: Main_Guide/MCM_Example_Session.md
      - Sidechain Session: Main_Guide/SCM_Example_Session.md
    - Going Farther: Main_Guide/Going_Farther.md